spring:
  mail:
    host: em5737.support@zenflouu.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  sendgrid:
    api-key: ${SENDGRID_API_KEY}
  data:
    mongodb:
      uri: mongodb+srv://destiny:nojKSRsW9qI0pKtl@cluster0.b0dfc.mongodb.net/zenflouu-api-db
      database: zenflouu-api-db
  auth:
    jwt:
      secret: ${JWT_SECRET}
      expiration: 86400000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

application:
  client-origin-url: ${CLIENT_ORIGIN_URL}

server:
  error:
    whitelabel:
      enabled: false
  port: ${PORT}

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  logging:
    level:
      org.springframework.web.reactive.function.client: DEBUG
      org.springframework.data.mongodb.core.MongoTemplate: DEBUG
