spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OKTA_OAUTH2_ISSUER}
          audience: ${OKTA_OAUTH2_AUDIENCE}

application:
  client-origin-url: ${CLIENT_ORIGIN_URL}

server:
  error:
    whitelabel:
      enabled: false
  port: ${PORT}

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false