spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  mail:
    host: em5737.support@zenflouu.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  sendgrid:
    api-key: ${SENDGRID_API_KEY}
  data:
    mongodb:
      uri: ${MONGODB_URI
      database: zenflouu-api-db
  auth:
    jwt:
      secret: ${JWT_SECRET}
      expiration: 86400000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  azure:
    storage:
      connection-string: ${AZURE_STORAGE_CONNECTION_STRING}
      account-name: ${AZURE_STORAGE_ACCOUNT_NAME}
      account-key: ${AZURE_STORAGE_ACCOUNT_KEY}
      container-name: ${AZURE_STORAGE_COI_CONTAINER_NAME}

application:
  client-origin-url: ${CLIENT_ORIGIN_URL}

server:
  error:
    whitelabel:
      enabled: false
  port: ${PORT}

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  logging:
    level:
      org.springframework.web.reactive.function.client: DEBUG
      org.springframework.data.mongodb.core.MongoTemplate: DEBUG
